version: '3.1'

services:

  db:
    image: postgres
    container_name: repo_local_pgdb
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata: